name: practice automation workflow

on:
  push:
    branches:
      - winget-automation

jobs:
  practice-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout winget-automation
        uses: actions/checkout@v2
        with:
          ref: winget-automation
          # we need the full history for the git tag command, so fetch all the branches
          fetch-depth: 0

      # Set up Node.js environment, pay attention to the version
      # Some features might not be available in older versions
      - name: Create node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: "21"

      # We set the latest tag as an environment variable before we use it in the next steps
      # note that we have to echo the variable to the environment file to make it available in the next steps
      - name: Set latest tag
        run: |
          echo "Setting latest tag"
          latestTag=$(git tag --list --sort=version:refname 'v*' | tail -1)
          # Remove the 'v' from the tag
          latestTag=${latestTag#v}
          echo "LATEST_HEADLAMP_TAG=$latestTag" >> $GITHUB_ENV
          echo $latestTag

      # Install winget dependencies
      # It is good to have a separate step for installing dependencies
      - name: Install winget dependencies
        run: |
          cd $GITHUB_WORKSPACE/app/windows/winget
          npm install

      # Run the winget script
      # We use the environment variable we set in the previous step
      # note: the $latestTag is not being set here and thus does not exist in the environment
      # this is because the environment is not shared between steps
      # that is why we have to echo the variable to the environment file in the previous step
      - name: Run winget script
        run: |
          echo "Running winget script"
          echo "Repository: ${{ github.repository }}"
          echo "Workspace: ${GITHUB_WORKSPACE}"
          echo $GITHUB_WORKSPACE
          pwd
          # WONT WORK ->  echo "Latest tag: $latestTag"
          # WONT WORK ->  echo "latestTag: ${latestTag}"
          # WONT WORK ->  echo $latestTag
          echo "LATEST_HEADLAMP_TAG: $LATEST_HEADLAMP_TAG"
          echo "LATEST_HEADLAMP_TAG: ${LATEST_HEADLAMP_TAG}"
          echo ${LATEST_HEADLAMP_TAG}
          cd $GITHUB_WORKSPACE/app/windows/winget
          node winget-create.js $LATEST_HEADLAMP_TAG $GITHUB_WORKSPACE/app/windows/winget

      - name: Print script finished
        run: |
          echo "Script finished"
          pwd
          cd $GITHUB_WORKSPACE/app/windows/winget
          ls
